development:
  adapter: mysql
  database: vcs_dev
  pool: 2
  timeout: 5000
  username: root
  password: root

test:
  adapter: mysql
  database: vcs_test
  pool: 2
  timeout: 5000
  username: root
  password: root

production:
  adapter: mysql
  database: vcs_prod
  pool: 2
  timeout: 5000
  username: root
  password: root
